name: CI/CD Pipeline for Accessory Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create models directory (if not exist)
        run: |
          mkdir -p models

      - name: Train model
        run: |
          python train_model.py

      - name: Add trained model to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add models/electro_accessory_model.tflite models/electro_accessory_model.keras
          git commit -m "Update trained model via GitHub Actions"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
